### PR TITLE
Added Responsive Layout Flex Html & css Files 

### PR DESCRIPTION
**Pull request by Himanshurajput757**

### CODE REVIEW

**Review by Vishal-raj-1 — CHANGES_REQUESTED** [review]
why are you changing in other's files?

**Comment by Vishal-raj-1** [comment]
Any Update?

**Comment by Himanshurajput757** [comment]
I am not Changing Other Files only changes my portfolio css & html code

**Comment by Vishal-raj-1** [comment]
image

refer this

**Pull request closed without merging**
